#!/bin/env bash
clear
set -e

# === Banner / Title ===
echo -e "\033[1;35m
   █████╗ ██████╗  ██████╗██╗  ██╗
  ██╔══██╗██╔══██╗██╔════╝██║  ██║
  ███████║██████╔╝██║     ███████║
  ██╔══██║██╔══██╗██║     ██╔══██║
  ██║  ██║██║  ██║╚██████╗██║  ██║
  ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝
\033[0m"

echo -e "\033[1;36mWelcome to ArcHypr Setup Installer\033[0m"
echo

read -p "Do you want to start the setup? (y/n): " confirm

if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
	echo -e "\033[1;33mSetup canceled.\033[0m"
	exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

bash "$SCRIPT_DIR/scripts/packages.sh" # Not same folder call script

# source "$SCRIPT_DIR/archyprsetup.sh" # Same folder call script
bash "$SCRIPT_DIR/scripts/archysetup.sh" # Not same folder call script

echo
echo "✅ Arch Hyprland Config and Packages Install All setup complete!"
