# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Blue                        │
# └────────────────────────────────────────────┘

$accent  = rgba(89b4faff)
$accent2 = rgba(b4befeff)
$border  = rgba(6c7086aa)
