# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Flamingo                    │
# └────────────────────────────────────────────┘
$accent  = rgba(f2cdcdff)
$accent2 = rgba(f5c2e7ff)
$border  = rgba(6c7086aa)
