# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Frappe                      │
# └────────────────────────────────────────────┘

$accent  = rgba(8caaeeee)
$accent2 = rgba(f4b8e4ee)
$border  = rgba(626880aa)
