# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Green                       │
# └────────────────────────────────────────────┘

$accent  = rgba(a6e3a1ff)
$accent2 = rgba(94e2d5ff)
$border  = rgba(6c7086aa)
