# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Lavender                    │
# └────────────────────────────────────────────┘

$accent  = rgba(b4befeff)
$accent2 = rgba(cba6f7ff)
$border  = rgba(6c7086aa)
