# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Maroon                      │
# └────────────────────────────────────────────┘


$accent  = rgba(eba0acff)
$accent2 = rgba(f38ba8ff)
$border  = rgba(6c7086aa)
