# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : MochaDark                   │
# └────────────────────────────────────────────┘


$accent  = rgba(89b4faee)
$accent2 = rgba(f5c2e7ee)
$border  = rgba(6c7086aa)
