# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Peach                       │
# └────────────────────────────────────────────┘


$accent  = rgba(fab387ff)
$accent2 = rgba(f9e2afff)
$border  = rgba(6c7086aa)
