# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Pink                        │
# └────────────────────────────────────────────┘


$accent  = rgba(f5c2e7ff)
$accent2 = rgba(cba6f7ff)
$border  = rgba(6c7086aa)
