# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : RoseWater                   │
# └────────────────────────────────────────────┘


$accent  = rgba(f5e0dcee)
$accent2 = rgba(f2cdcdff)
$border  = rgba(6c7086aa)
