# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Sky                         │
# └────────────────────────────────────────────┘


$accent  = rgba(89dcebff)
$accent2 = rgba(74c7ecff)
$border  = rgba(6c7086aa)
