# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Teal                        │
# └────────────────────────────────────────────┘


$accent  = rgba(94e2d5ff)
$accent2 = rgba(89dcebff)
$border  = rgba(6c7086aa)
