# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │ Colors       : Yellow                      │
# └────────────────────────────────────────────┘


$accent  = rgba(f9e2afff)
$accent2 = rgba(a6e3a1ff)
$border  = rgba(6c7086aa)
