# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │                                            │
# └────────────────────────────────────────────┘
# ┌───────────────────────────────────────────────────────────────────────────┐
# │                           Applications Style                              │
# └───────────────────────────────────────────────────────────────────────────┘

roundess = 2

border_width = 0

reduce_motion = false
