# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │                                            │
# └────────────────────────────────────────────┘
# ┌───────────────────────────────────────────────────────────────────────────┐
# │                         INPUT / Keyboard / Mouse                          │
# └───────────────────────────────────────────────────────────────────────────┘

input {
    # ┌────────────────────────────────────────────┐
    # │  Keyboard Layout US,Myanmar                │
    # └────────────────────────────────────────────┘
    kb_layout = us,mm 
    kb_variant =
    kb_model =
    kb_options = 
    kb_rules =

    # Key repeat (Wayland native)
    repeat_rate = 35
    repeat_delay = 200

    # ┌────────────────────────────────────────────┐
    # │                Mouse / Focus               │
    # └────────────────────────────────────────────┘
    follow_mouse = 1          # focus follows cursor
    sensitivity = 0           # -1.0 ~ 1.0 (0 = neutral)

    # ┌────────────────────────────────────────────┐
    # │              Touchpad                      │
    # └────────────────────────────────────────────┘
    touchpad {
        natural_scroll = false
        disable_while_typing = true
        tap-to-click = true
        drag_lock = false
        clickfinger_behavior = true
        middle_button_emulation = true
    }
}

    # ┌────────────────────────────────────────────┐
    # │                    CURSOR                  │
    # └────────────────────────────────────────────┘
cursor {
    inactive_timeout = 30     # auto-hide cursor
    no_hardware_cursors = true
}


# Example mouse (change name with: hyprctl devices)
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}


# ┌───────────────────────────────────────────────────────────────────────────┐
# │                          SCROLLING LAYOUT                                  │
# └───────────────────────────────────────────────────────────────────────────┘

general {
    layout = scrolling
}

scrolling {
    column_width = 0.667
    focus_fit_method = 1
    follow_focus = true
    follow_min_visible = 1.0
    explicit_column_widths = 0.334, 0.5, 0.667, 1.0
    direction = "right"
}
