# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │                                            │
# └────────────────────────────────────────────┘
# ┌────────────────────────────────────────────┐
# │                    MISC                    │
# └────────────────────────────────────────────┘
misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    vfr = true
    vrr = 1
}

