# ┌────────────────────────────────────────────┐
# │ AuthorModify : KyawNyeinThant              │
# │ Github       : kntlifelovelive             │
# │ Date         : 2026 , March, 13            │
# │                                            │
# └────────────────────────────────────────────┘
# ┌────────────────────────────────────────────┐
# │               MONITORS SETUP               │
# └────────────────────────────────────────────┘

# monitor=eDP-1,1366x768@60,auto,1
# monitor=,preferred,auto,auto

monitor =eDP-1,1366x768@60,auto,1

